"use client";
import { useEffect } from "react";
import "./globals.css";

export const metadata = {
  title: "Satria Siliwangi Basketball",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    const abortController = new AbortController();
    return () => {
      abortController.abort();
    };
  }, []);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
